/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://raw.githubusercontent.com/oberasoftware/zwave/master/repo/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:1.1.9.RELEASE")
    implementation("com.google.guava:guava:18.0")
    implementation("com.neuronrobotics:nrjavaserial:3.9.3")
    implementation("com.oberasoftware:obera-base:1.0")
    testImplementation("org.mockito:mockito-core:1.9.5")
    testImplementation("junit:junit:4.11")
}

group = "com.oberasoftware"
version = "1.0-SNAPSHOT"
description = "Oberasoftware ZWave Library"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
